services:
  mongodb:
    image: mongo:6.0
    container_name: n8n-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-n8n}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://${MONGO_USERNAME:-root}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE:-n8n}?authSource=admin
      - N8N_BASIC_AUTH_ACTIVE=${N8N_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_USERNAME}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
    volumes:
      - ${N8N_DATA_PATH:-~/.n8n}:/home/node/.n8n
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: